export const purchaseOrders = [
  {
    id: 1,
    orderedDate: "Jan 4, 2022 ",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "NA",
    status: { label: "Drafted", color: "gray" },
    actions: ["edit", "delete"],
  },
   {
    id: 2,
    orderedDate: "Jan 4, 2022  ",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "Jan 4, 2022  11:30 AM",
    status: { label: "Pending", color: "yellow" },
    actions: ["pdf", "refresh"],
  },
    {
    id: 3,
    orderedDate: "Jan 4, 2022 ",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "Jan 4, 2022  11:30 AM",
    status: { label: "Received", color: "green" },
    actions: ["edit", "delete"],
  },
  {
    id: 4,
    orderedDate: "Jan 4, 2022 ",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "NA",
    status: { label: "Rejected", color: "red" },
    actions: ["pdf", "unavailable"],
  },
  {
    id: 5,
    orderedDate: "Jan 4, 2022",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "Jan 4, 2022  11:30 AM",
    status: { label: "In Transit", color: "purple" },
    actions: ["pdf", "location"],
  },
  {
    id: 6,
    orderedDate: "Jan 4, 2022 ",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "NA",
    status: { label: "Drafted", color: "gray" },
    actions: ["edit", "delete"],
  },
    {
    id: 7,
    orderedDate: "Jan 4, 2022",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "Jan 4, 2022  11:30 AM",
    status: { label: "In Transit", color: "purple" },
    actions: ["pdf", "location"],
  },
  {
    id: 8,
    orderedDate: "Jan 4, 2022",
    orderTime : "11:30 AM",
    purchaseOrderId: "TUX001234",
    supplierId: "REMA0123",
    eta: "Jan 4, 2022  11:30 AM",
    status: { label: "Received", color: "green" },
    actions: ["edit", "delete"],
  }

];
